name: Deploy to test Supabase

on:
  push:
    branches: [dev]

jobs:
  deploy:
    uses: ./.github/workflows/deploy-supabase.yml
    with:
      project-ref: ofvfasdgdwkehdcjugnf
    secrets:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD_TEST }}
